services:
  - type: web
    name: flask-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: pdf-storage
      mountPath: /opt/render/project/src/pdf_output
      sizeGB: 10