services:
  - type: web
    name: flask-script-main
    env: python
    buildCommand: |
      # Install Chrome
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable
      
      # Install ChromeDriver
      CHROME_VERSION=$(google-chrome --version | cut -d " " -f3 | cut -d "." -f1)
      CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
      wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
      unzip chromedriver_linux64.zip
      mv chromedriver /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PATH
        value: /usr/local/bin:${PATH}
    disk:
      name: pdf-storage
      mountPath: /opt/render/project/src/pdf_output
      sizeGB: 1 