services:
  - type: web
    name: waqf-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
    healthCheckPath: /
    numInstances: 1 